// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function() {
    var canvas, canvasBox, ctx;
    canvas = document.createElement('canvas');
    canvas.width = 400;
    canvas.height = 400;
    canvasBox = document.getElementById('canvas-box');
    canvasBox.innerHTML = "";
    canvasBox.appendChild(canvas);
    ctx = canvas.getContext('2d');
    ctx.setTransform(1, 0, 0, -1, canvas.width / 2, canvas.height / 2);
    return canvas;
  };

}).call(this);
