// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function() {
    var canvas, ctx;
    canvas = document.getElementById('canvas');
    ctx = canvas.getContext('2d');
    ctx.restore();
    ctx.save();
    ctx.setTransform(1, 0, 0, -1, canvas.width / 2, canvas.height / 2);
    return canvas;
  };

}).call(this);
