// Generated by CoffeeScript 1.6.2
(function() {
  this.HALT = 1;

  this.POP = 2;

  this.LDCONST = 3;

  this.LDLOCAL = 4;

  this.LDGLOBAL = 5;

  this.STLOCAL = 6;

  this.STGLOBAL = 7;

  this.CALL = 8;

  this.RET = 9;

  this.JT = 10;

  this.JF = 11;

  this.JMP = 12;

  this.ADD = 13;

  this.SUB = 14;

  this.MUL = 15;

  this.DIV = 16;

  this.MOD = 17;

  this.DELLOCAL = 18;

  this.DELGLOBAL = 19;

  this.INC = 20;

  this.DEC = 21;

  this.POS = 22;

  this.NEG = 23;

  this.LSHIFT = 24;

  this.URSHIFT = 25;

  this.RSHIFT = 26;

  this.LTE = 27;

  this.GTE = 28;

  this.LT = 29;

  this.GT = 30;

  this.EQ = 31;

  this.NEQ = 32;

  this.NOT = 33;

  this.BNEG = 34;

  this.BAND = 35;

  this.BXOR = 36;

  this.BOR = 37;

  this.AND = 38;

  this.OR = 39;

  this.ROT = 40;

  this.DUP = 41;

  this.TYPEOF = 42;

  this.NRET = 43;

}).call(this);
